services:
  mobilizasp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mobilizasp
    ports:
      - "4001:4001"
    env_file:
      - .env
    volumes:
      - ./.waba-session:/app/.waba-session
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4001/healthz', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
